# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-116e5a4e-ddb7-4284-a6a0-d99e0e5159a2";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-116e5a4e-ddb7-4284-a6a0-d99e0e5159a2".device = "/dev/disk/by-uuid/116e5a4e-ddb7-4284-a6a0-d99e0e5159a2";

boot.initrd.luks.devices."crypt-home" = {
  device = "/dev/disk/by-uuid/574359cf-1164-466d-9180-6d2af33a88e9";
};

fileSystems."/home" = {
  device = "/dev/mapper/crypt-home";
  fsType = "ext4";
};
  swapDevices =
    [ { device = "/dev/mapper/luks-2fd5c54f-4fb5-42de-b05e-cf759e15018a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
