# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/22708146-66e4-41e2-ae4c-39a1d6b8baa8";
      fsType = "ext4";
    };
boot.initrd.luks.devices."luks-0e714a04-6ed7-45e4-867d-94baa254c6a7".device = "/dev/disk/by-uuid/0e714a04-6ed7-45e4-867d-94baa254c6a7";
boot.initrd.luks.devices."home".device = "/dev/disk/by-uuid/574359cf-1164-466d-9180-6d2af33a88e9";	
  fileSystems."/" =
    { device = "/dev/mapper/luks-0e714a04-6ed7-45e4-867d-94baa254c6a7";
      fsType = "ext4";
    };

    fileSystems."/home" = {
  device = "/dev/mapper/home";  # Nome do dispositivo desbloqueado
  fsType = "ext4";              # Tipo de sistema de arquivos (se for ext4, por exemplo)
};
    swapDevices =
    [ { device = "/dev/disk/by-uuid/b8dee12b-d8fe-466c-960d-53df66e31ff5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
